apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    # Use these arguments to force MySQL to use minimal memory
    args:
      - "--performance-schema=OFF"
      - "--innodb-buffer-pool-size=16M"
      - "--innodb-log-buffer-size=1M"
      - "--max-connections=10"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "400Mi" # Prevents the Pod from growing until it gets OOMKilled
    env:                                
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: "webapp"
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP